version: "3.8"

services:
  # ----------------------------------------------------
  # 1. СЕРВІС БЕКЕНДУ (Flask)
  # ----------------------------------------------------
  web:
    build: . # Створює образ з поточного каталогу, використовуючи Dockerfile
    container_name: wayforpay_backend_web
    # ОНОВЛЕННЯ: Прокидаємо порт 5000 контейнера на порт 5078 хост-машини
    ports:
      - "5078:5000"
    depends_on:
      - db # Запуск після успішного запуску бази даних
    environment:
      # Змінні оточення, які Flask використовує для підключення до бази даних
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=jK56Dq$1
      - MYSQL_DATABASE=wayforpay_db
    restart: always

  # ----------------------------------------------------
  # 2. СЕРВІС БАЗИ ДАНИХ (MySQL)
  # ----------------------------------------------------
  db:
    image: mysql:8.0 # Використовуємо офіційний образ MySQL
    container_name: wayforpay_backend_db
    # Встановлюємо паролі та ім'я БД
    environment:
      MYSQL_ROOT_PASSWORD: jK56Dq$1 # Пароль для root користувача
      MYSQL_DATABASE: wayforpay_db # Ім'я бази даних для створення
    # Зберігаємо дані на хост-машині, щоб вони не втратилися після зупинки контейнера
    volumes:
      - db_data:/var/lib/mysql
    # Порт бази даних не прокидаємо, оскільки доступ до неї потрібен лише сервісу 'web'
    restart: always

volumes:
  db_data:
